# frontend/Dockerfile
FROM node:20

WORKDIR /app

# Copiar package.json y package-lock.json 
COPY package*.json ./

# Instalar todas las dependencias
RUN npm install --legacy-peer-deps

# Copiar el resto del código de la aplicación
COPY . .

# Exponer puerto
EXPOSE 5173

# Iniciar la aplicación
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]