services:
  postgres:
    image: postgres:latest
    container_name: dualeat_postgres
    environment:    
      - POSTGRES_DB=DualEat
      - POSTGRES_USER=DualEat
      - POSTGRES_PASSWORD=DualEat21102504
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - dualeat-network

  pgadmin:
    image: dpage/pgadmin4:latest 
    container_name: dualeat_pgadmin
    environment:     
      - PGADMIN_DEFAULT_EMAIL=dualeat@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - 5050:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - dualeat-network

  backend:
    build:
      context: ./backend       
      dockerfile: Dockerfile   
    platform: linux/amd64
    container_name: dualeat_backend
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://DualEat:DualEat21102504@postgres:5432/DualEat
      - CORS_ORIGIN=http://localhost:5173  # Cambiar a puerto 5173
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - dualeat-network
    command: ["sh", "-c", "npx prisma db push && npm run dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: dualeat_frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000  # Para Vite usa VITE_ prefix
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dualeat-network

networks:
  dualeat-network:
    driver: bridge