import { ROUTES } from "./constants";

export const OUT_NAVBAR_ROUTES = {
  LOGIN: ROUTES.AUTH.LOGIN,
  REGISTER: ROUTES.AUTH.REGISTER,
  REGISTER_LOCAL: ROUTES.AUTH.REGISTER_LOCAL,
  ONBOARDING: ROUTES.AUTH.ONBOARDING,
  RESET_PASSWORD: ROUTES.AUTH.RESET_PASSWORD,
  ADMIN: ROUTES.ADMIN.BUSINESS_CREATION,
  FOOD_CATEGORIES: ROUTES.ADMIN.FOOD_CATEGORIES,
  LOCALS: ROUTES.ADMIN.LOCALS,
  ERROR: ROUTES.ERROR
}