import { ROUTES } from "./constants";

export const NAVBAR_ROUTES = [
  { path: ROUTES.PUBLIC.ABOUT_US, label: "Sobre nosotros" },
  { path: `${ROUTES.PUBLIC.HOME}#Funcionalidades`, label: "Funcionalidades" },
  { path: ROUTES.PUBLIC.BUSINESS, label: "Para negocios" },
];

export const OUT_NAVBAR_ROUTES = {
  LOGIN: ROUTES.AUTH.LOGIN,
  REGISTER: ROUTES.AUTH.REGISTER,
  REGISTER_LOCAL: ROUTES.AUTH.REGISTER_LOCAL,
  ONBOARDING: ROUTES.AUTH.ONBOARDING,
  RESET_PASSWORD: ROUTES.AUTH.RESET_PASSWORD,
  ADMIN: ROUTES.ADMIN.BUSINESS_CREATION,
  FOOD_CATEGORIES: ROUTES.ADMIN.FOOD_CATEGORIES,
  LOCALS: ROUTES.ADMIN.LOCALS,
  ERROR: ROUTES.ERROR
}